language: bash
sudo: required
env:
  matrix:
  - DEPLOY_ENVIRONMENT=production DEPLOY_BRANCH=master
  - ""
services:
- docker
script:
- ./continuous_deployment_travis.sh
- if [ -z "${DEPLOY_ENVIRONMENT}" ]; then ./test.sh; fi
notifications:
  email: false
