language: bash
sudo: required
env:
  matrix:
  - DEPLOY_ENVIRONMENT=staging DEPLOY_BRANCH=master
  - DEPLOY_ENVIRONMENT=production DEPLOY_TAGS=true
services:
- docker
script:
- ./continuous_deployment_travis.sh
notifications:
  email: false
