steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - "-c"
  - "docker pull gcr.io/midbarrn/midburn-chatops-latest || true"
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - "--cache-from"
  - gcr.io/midbarrn/midburn-chatops-latest
  - "-t"
  - gcr.io/midbarrn/midburn-chatops-latest
  - "-t"
  - "${_IMAGE_TAG}"
  - "."
images:
- gcr.io/midbarrn/midburn-chatops-latest
- "${_IMAGE_TAG}"
